### ISSUE TITLE
Why all_fea = torch.cat((all_fea, torch.ones(all_fea.size(0), 1)), 1) ?

### ISSUE THREAD

**Issue by yyaaa1** [tim-learn/SHOT#13]
Hello, after read the previous answers of this question, I am still confused about this operation. Why should we explicitly add 1 as bias? As far as I know, the linear transformation with bias on will not change the size of our feature, so I feel it is unnecessary to add a bias manually. 

Would you please further explain this for me?

Thx

**Comment by tim-learn** [comment]
@yyaaa1 for the last classifier[w, b], if we add 1, then the new features will be close to the [w_k, b_k] via the cosine distance, which is adopted in this paper.

**Comment by siaimes** [comment]
@tim-learn 

[        nn.init.zeros_(m.bias)](https://github.com/tim-learn/SHOT/blob/7cebb390194215823b435b0723c7b342ae62b42b/object/network.py#L24)

I see that bias is initialized to 0 in your code, which is equivalent to no bias, isn’t it?

**Comment by bluelg** [comment]
> @tim-learn
> 
> [ nn.init.zeros_(m.bias)](https://github.com/tim-learn/SHOT/blob/7cebb390194215823b435b0723c7b342ae62b42b/object/network.py#L24)
> 
> I see that bias is initialized to 0 in your code, which is equivalent to no bias, isn’t it?

I think the bias would have a non-zero value after learning, maybe you can check that value.

**Comment by tim-learn** [comment]
> @tim-learn
> 
> [ nn.init.zeros_(m.bias)](https://github.com/tim-learn/SHOT/blob/7cebb390194215823b435b0723c7b342ae62b42b/object/network.py#L24)
> 
> I see that bias is initialized to 0 in your code, which is equivalent to no bias, isn’t it?

I think the bias would have a non-zero value after learning, maybe you can check that value.
