### ISSUE TITLE
problem about office-caltech

### ISSUE THREAD

**Issue by ygjwd12345** [tim-learn/SHOT#15]
I don't find caltech_list.txt.
Would you mind share this file?
Meanwhile, your link of Office-Caltech is different from https://github.com/jindongwang/transferlearning/blob/master/data/dataset.md#office+caltech. Is there something wrong?

**Comment by tim-learn** [comment]
> I don't find caltech_list.txt.
> Would you mind share this file?
> Meanwhile, your link of Office-Caltech is different from https://github.com/jindongwang/transferlearning/blob/master/data/dataset.md#office+caltech. Is there something wrong?

Hi, Office-Caltech consists of 10 shared classes between the Caltech-101 dataset and Office-31 dataset. I think it is the same as your suggested link. After you download the original datasets, you need to generate the txt files by yourself, which sounds not difficult.

**Comment by tim-learn** [comment]
> I don't find caltech_list.txt.
> Would you mind share this file?
> Meanwhile, your link of Office-Caltech is different from https://github.com/jindongwang/transferlearning/blob/master/data/dataset.md#office+caltech. Is there something wrong?

Hi, Office-Caltech consists of 10 shared classes between the Caltech-256 dataset and Office-31 dataset. I think it is the same as your suggested link. After you download the original datasets, you need to generate the txt files by yourself, which sounds not difficult.
