### ISSUE TITLE
For more details about "modify the path of images in each '.txt' under the folder './object/data/'."

### ISSUE THREAD

**Issue by Anthem0w0** [tim-learn/SHOT#2]
Could you elaborate more carefully on how to modify the .txt file in the /object/data directory?
Where are the '.txt' files? (Maybe the image_list.txt in each folder?) Like the office dataset, there is no 'amazon.txt' in the 'domain_adaptation_images.tar.gz'.
And how to do this?
This is a great job, looking forward to your reply!

**Comment by tim-learn** [comment]
@Anthem0w0 
![r](https://user-images.githubusercontent.com/66909626/86093518-a95be000-bae1-11ea-93a3-8b5b39be1183.JPG)
you need to generate these txt files by yourself like those above.

**Comment by Anthem0w0** [comment]
OK, thank you for your reply~
However, due to some unknown reasons, I cannot view the picture in your reply. Could you mail it to 820263118@qq.com?

**Comment by tim-learn** [comment]
> OK, thank you for your reply~
> However, due to some unknown reasons, I cannot view the picture in your reply. Could you mail it to 820263118@qq.com?

each line in the txt file contains the image path and its label, and it looks like "/Checkpoint/liangjian/da_dataset/office_home/Art/Alarm_Clock/00001.jpg 0"
