### ISSUE TITLE
can not reproduce the result of VisDA-C

### ISSUE THREAD

**Issue by Wang-xd1899** [tim-learn/SHOT#25]
Hi, thanks for your awesome work! I just clone this repo, and follow the recommended lines:
```
 python image_source.py --trte val --output ckps/source/ --da uda --gpu_id 0 --dset VISDA-C --net resnet101 --lr 1e-3 --max_epoch 10 --s 0
 python image_target.py --cls_par 0.3 --da uda --dset VISDA-C --gpu_id 0 --s 0 --output_src ckps/source/ --output ckps/target/ --net resnet101 --lr 1e-3 
```
After trained on source domain, I get the good source-model acc (47.62%) better than paper (acc 46.6%)
<img width="500" alt="截屏2021-12-16 下午3 39 27" src="https://user-images.githubusercontent.com/44627574/146328451-864c3f3a-2675-4f9a-9441-8a1cab9549bf.png">
But I use the command to adapt the model to target domain (clas_par=0.3, seed=2020), the result is only about 75%. The log can be found [here](https://drive.google.com/file/d/1DG6sYIAnpmFro6cnMaMcpF1-waHX7kMf/view)

Any problem in my training process? Look forward to your reply.

Best wishes!

**Comment by tim-learn** [comment]
@Wang-xd1899 Hi, it looks that the source-only result is normal, and the log sounds okay too. Lower results may be resulted from the environment? (The biggest difference lies in the last class "truck"). You can use the same environment with mine and try again.
