### ISSUE TITLE
Pretrained checkpoints

### ISSUE THREAD

**Issue by jmiemirza** [tim-learn/SHOT#27]
Hi, 

Thank you for maintaining the repo this nicely. However, would it be possible to provide some pretrained checkpoints for 'VISDA-C' or 'Office-31' datasets? 

Thanks and Best Regards, 
Mirza.

**Comment by tim-learn** [comment]
> Hi,
> 
> Thank you for maintaining the repo this nicely. However, would it be possible to provide some pretrained checkpoints for 'VISDA-C' or 'Office-31' datasets?
> 
> Thanks and Best Regards, Mirza.

Hi, Mirza

   Sorry for the late reply due to the busy period for CVPR rebuttal. Maybe one week later, I would like to upload the pretrained checkpoints. I will notify you once they are okay for downloading.

Best,

Tim

**Comment by tim-learn** [comment]
@jmiemirza pls refer https://github.com/tim-learn/SHOT/blob/master/pretrained-models.md for the pre-trained source models.
