### ISSUE TITLE
use domainnet dataset

### ISSUE THREAD

**Issue by Chy-dev249** [tim-learn/SHOT#28]
Hi ,thanks for your excellent work. 
Have you ever try to work on the domainNet dataset ? SInce I can't get satisfied result by changing the dataset only.

**Comment by tim-learn** [comment]
> Hi ,thanks for your excellent work. Have you ever try to work on the domainNet dataset ? SInce I can't get satisfied result by changing the dataset only.

Hi, maybe you need to change the learning rate and adjust the weights of different loss objectives by yourself since DomainNet owns an extremely imbalanced label distribution.  

Best

**Comment by Chy-dev249** [comment]
Hi, thanks for your response. But I still want to know whether the kmeans is still work in domainnet. (From my experiment  result, I found it's not work well ) Since the number of classes is 345, the variable of k in kmeans has better to be a smaller one, like 8. Is it necessary to change another method to optimize the pseudo lable during the training process? Do you have any suggestions? Thank you very much！
Best

**Comment by tim-learn** [comment]
> Hi, thanks for your response. But I still want to know whether the kmeans is still work in domainnet. (From my experiment result, I found it's not work well ) Since the number of classes is 345, the variable of k in kmeans has better to be a smaller one, like 8. Is it necessary to change another method to optimize the pseudo lable during the training process? Do you have any suggestions? Thank you very much！ Best

You can try the updated code for DomainNet again.
