### ISSUE TITLE
Pretrained source model obtain random-level output

### ISSUE THREAD

**Issue by JiayuMaoReal** [tim-learn/SHOT#32]
pretrained source model about **office-home** obtain random-level output (directly test pretrained model on target domain, e.g. Ar->Cl 0.01786....)
but with the same code and loading setting about **office-31** get satisfactory result.
Maybe the pretrained model on **office-home** has something wrong?
Thank you

**Comment by tim-learn** [comment]
> pretrained source model about **office-home** obtain random-level output (directly test pretrained model on target domain, e.g. Ar->Cl 0.01786....) but with the same code and loading setting about **office-31** get satisfactory result. Maybe the pretrained model on **office-home** has something wrong? Thank you

Hi, sorry for the late reply. I check the files, they are correctly uploaded. Maybe you can test the model in the source domain, if the results are still inconsistent with those values in the corresponding text files. Maybe you need to train the source models by youself.

**Comment by JiayuMaoReal** [comment]
Hi! Thank for your help, I will try to train the source models.
