### ISSUE TITLE
Pseudo-labeling

### ISSUE THREAD

**Issue by dingyan1478** [tim-learn/SHOT#33]
I'm sorry to bother you!
In the process of generating pseudo tags, the target domain has no real tags, but in the process of code implementation, why are there labels = data [1]? What does this labels stand for?
![屏幕截图 2022-05-19 215500](https://user-images.githubusercontent.com/74007964/169310653-6597c80c-fa82-4364-8318-88ade73843a4.png)
If these labels are used, then where are the pseudo label?

**Comment by tim-learn** [comment]
> I'm sorry to bother you! In the process of generating pseudo tags, the target domain has no real tags, but in the process of code implementation, why are there labels = data [1]? What does this labels stand for? ![屏幕截图 2022-05-19 215500](https://user-images.githubusercontent.com/74007964/169310653-6597c80c-fa82-4364-8318-88ade73843a4.png) If these labels are used, then where are the pseudo label?

Hi, it is used to output the accuracy and is not used for the training process.
