### ISSUE TITLE
The test loader and the target loader are consistent

### ISSUE THREAD

**Issue by Xiaofu233** [tim-learn/SHOT#35]
Hello,
Firstly thanks for sharing the code to the community. I encountered some questions in my code reading process.

I find the test_dset_path and t_dset_path are the same in the code, that is to say, the test procedure in target domain uses the data that have been seen in the training process?

Thanks!

**Comment by tim-learn** [comment]
> Hello, Firstly thanks for sharing the code to the community. I encountered some questions in my code reading process.
> 
> I find the test_dset_path and t_dset_path are the same in the code, that is to say, the test procedure in target domain uses the data that have been seen in the training process?
> 
> Thanks!

In most UDA datasets, yes!
