### ISSUE TITLE
Is it wrong here? It seems that the updated part should be gt.

### ISSUE THREAD

**Issue by Anthem0w0** [tim-learn/SHOT#4]
![ffe7964769edcfef7127fa135e12495](https://user-images.githubusercontent.com/23754668/87846577-6ed8ac80-c903-11ea-959b-88b722489b47.png)

**Comment by bluelg** [comment]
Thanks for your nice reminder. We will revise this typo in the final version.

**Comment by bluelg** [comment]
@Anthem0w0 Thanks for your nice reminder. We will revise this typo in the final version.

**Comment by tim-learn** [comment]
@Anthem0w0 We will revise this typo in the final version. Thanks for your kind reminder!
