### ISSUE TITLE
Can't reproduce the results on Office-Home for PDA

### ISSUE THREAD

**Issue by Zysty** [tim-learn/SHOT#5]
Hi, thanks for your sharing!
I run your code on Office-Home dataset for PDA when source domain is the Art. (i.e., A->C, A->P, A->R). But they can not reproduce the results only except A->C.
I got the following results  on the three different seeds {2019, 2020, 2021}:
Source Only:
![image](https://user-images.githubusercontent.com/20252627/89891800-47c28180-dc08-11ea-9bc7-d4a73a6e9a35.png)
![image](https://user-images.githubusercontent.com/20252627/89890817-9242fe80-dc06-11ea-96a1-ce466799e2d1.png)
![image](https://user-images.githubusercontent.com/20252627/89890930-c8807e00-dc06-11ea-87fe-822f614e2bfd.png)

SHOT-IM
seed=2020:
![image](https://user-images.githubusercontent.com/20252627/89892006-9bcd6600-dc08-11ea-87b8-ccfdbf691e02.png)
![image](https://user-images.githubusercontent.com/20252627/89892019-9e2fc000-dc08-11ea-9550-6be751ecd9de.png)

Particularly, the performance on A->R gets worse as training time increases.
![image](https://user-images.githubusercontent.com/20252627/89892235-f4046800-dc08-11ea-9197-059b061f926a.png)

These results should be 
![image](https://user-images.githubusercontent.com/20252627/89892363-1eeebc00-dc09-11ea-8510-dc90caee2b4a.png)

I don't konw why it happens. Could you please tell me how to correctly reproduce results on PDA? Thanks.

**Comment by Zysty** [comment]
I can reproduce the results on office-home for PDA now!  
These experiments above were conducted on torch=1.1.0, python=3.6.2, torchvision=0.2.2.
Then I conduct corresponding experiments on the other server, on which torch=1.4.0,python=3.7.4, torchvision=0.5.0.
And it works!

Thank for your great work. But I still don't know why it happens...

**Comment by tim-learn** [comment]
> I can reproduce the results on office-home for PDA now!
> These experiments above were conducted on torch=1.1.0, python=3.6.2, torchvision=0.2.2.
> Then I conduct corresponding experiments on the other server, on which torch=1.4.0,python=3.7.4, torchvision=0.5.0.
> And it works!
> 
> Thank for your great work. But I still don't know why it happens...

Err, maybe the version of torchvision 0.2.2 is too old. It is really hard to explain why this happens....

**Comment by ygjwd12345** [comment]
> I can reproduce the results on office-home for PDA now!
> These experiments above were conducted on torch=1.1.0, python=3.6.2, torchvision=0.2.2.
> Then I conduct corresponding experiments on the other server, on which torch=1.4.0,python=3.7.4, torchvision=0.5.0.
> And it works!
> 
> Thank for your great work. But I still don't know why it happens...

but in the camera-ready the number increase to  57.1 78.1 81.5 68.0 78.2 78.1 67.4 54.9 82.2 73.3 58.8 84.3 71.8.  Do you reproduce this result?

**Comment by tim-learn** [comment]
> > I can reproduce the results on office-home for PDA now!
> > These experiments above were conducted on torch=1.1.0, python=3.6.2, torchvision=0.2.2.
> > Then I conduct corresponding experiments on the other server, on which torch=1.4.0,python=3.7.4, torchvision=0.5.0.
> > And it works!
> > Thank for your great work. But I still don't know why it happens...
> 
> but in the camera-ready the number increase to 57.1 78.1 81.5 68.0 78.2 78.1 67.4 54.9 82.2 73.3 58.8 84.3 71.8. Do you reproduce this result?

Hi, the results you mentioned is SHOT for closed-set UDA.

**Comment by roysubhankar** [comment]
> I can reproduce the results on office-home for PDA now! These experiments above were conducted on torch=1.1.0, python=3.6.2, torchvision=0.2.2. Then I conduct corresponding experiments on the other server, on which torch=1.4.0,python=3.7.4, torchvision=0.5.0. And it works!
> 
> Thank for your great work. But I still don't know why it happens...

Hi @Zysty can you please share with us a list of all the packages and their versions (pip list or conda list) which you used for running the experiments? I am still struggling to reproduce the numbers as reported in the paper. Thank you in advance.
